---
title: "Tests for simulations"
author: "Erik Ortiz Covarrubias"
date: "2023-06-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

source("sim_dgp_fn.R")
source("sim_montecarlo_fn.R")

```


# Testing the functions

Setup


```{r}

n <- 30
T <- 12
beta <- c(0.5,0.5)

```


1. `generate_x` & `shift_mean(X)`


```{r }

X <- generate_X(T,n)
stopifnot(dim(X) == c(T*n,2))
X_shifted <- shift_mean(X)
stopifnot(dim(X_shifted) == c(T*n,2))


X <- shift_mean(X)

group_size <- n*T/3

colMeans(X[1:group_size,])
colMeans(X[(1 + group_size):(2*group_size),])
colMeans(X[(1+ 2*group_size):(3*group_size),])
```


3. `generate_V*`


```{r}

# 0. Generate vectors of interest

v_list <- list()

V_list <- list(V1 = generate_V1(T, n),
              V2 = generate_V2(T, n),
              V3 = generate_V3(T, n),
              V4 = generate_V4(T, n),
              V5 = generate_V5(T, n),
              V6 = generate_V6(T, n))

# 1. Perform the length and NA checks using a loop

for (i in 1:length(V_list)) {
  stopifnot(length(V_list[[i]]) == T*n)
  stopifnot(!anyNA(V_list[[i]]))
}

# 2. Checking that the time-varying effects are correctly specified

for (i in 1:length(V_list)) {
  interval <- sample(0:(n-1), 1)
  start <- interval * T + 1
  end <- (interval + 1) * T
  plot(1:T, V_list[[i]][start:end], type = "l", xlab = "Time", ylab = "Individual Effects",
       main = paste("Individual Effects (V",i,") over Time - Interval:", interval))
}

```


4. `endogenous_X`

```{r}
X <- generate_X(T, n)
X <- shift_mean(X)

DGP = "K4"
  
# Create individual effects according to specified DGP
  if (DGP == "K1") {
    V <- generate_V1(T, n)
  } else if (DGP == "K2") {
    V <- generate_V2(T, n)
  } else if (DGP == "K3") {
    V <- generate_V3(T, n)
  } else if (DGP == "K4") {
    V <- generate_V4(T, n)
  }
  
  # Create endogenous regressors, when specified

X <- endogenous_X(T, n, X, V)

cor(X,V)


```

5. `generate_panel_errors`

```{r}

# 1. Homoskedastic

e <- generate_panel_errors(T, n, X, error = "homo") 

plot(X[,2], e, type = "p", xlab = "Observation", ylab = "Error", main = "Panel Errors")

# 2. Heteroskedastic 

e <- generate_panel_errors(T, n, X, error = "hetero") 

plot(X[,2], e, type = "p", xlab = "Observation", ylab = "Error", main = "Panel Errors")


# 2. Autocorrelated errors

e <- generate_panel_errors(T, n, X, error = "autocorr", rho = 0.5) 

plot(e[1:T], type = "l", xlab = "Observation", ylab = "Error", main = "Panel Errors")
```


6.`create_nT_frame` 

```{r}

n <- 300
T <- 30


X <- generate_X(T, n)
X <- shift_mean(X)

DGP = "K4"
  
# Create individual effects according to specified DGP
  if (DGP == "K1") {
    V <- generate_V1(T, n)
  } else if (DGP == "K2") {
    V <- generate_V2(T, n)
  } else if (DGP == "K3") {
    V <- generate_V3(T, n)
  } else if (DGP == "K4") {
    V <- generate_V4(T, n)
  }

e <- generate_panel_errors(T, n, X, error = "homo")

Y <- X %*% beta + V + e

create_plm_data(T, n, Y, X, V)

```


7. `DataGeneratingFunction`

```{r}

library(plm)

n <- 30
T <- 12


beta <- c(0.5,0.5)

data <- DataGeneratingFunction(T, n, beta = beta, DGP = "B1" , endogenous = FALSE, error = "autocorr")
data_plm <- data[["plm"]]
data_Tn <-  data[["Tn"]]

KSS.fit <- KSS(data_Tn$Y ~ data_Tn$X_1 + data_Tn$X_2 -1, CV = TRUE)
summary(KSS.fit)
plot(summary(KSS.fit))


Eup.fit <- Eup(data_Tn$Y ~ data_Tn$X_1 + data_Tn$X_2 -1, dim.criterion = "PC3")
summary(Eup.fit)
plot(summary(Eup.fit))

plm_fit <- plm(data_plm$Y ~ data_plm$X_1 + data_plm$X_2 -1, data = data_plm,  model = "within")
summary(plm_fit)
```
```{r}

source("sim_dgp_fn.R")
source("sim_montecarlo_fn.R")

n <- 30
T <- 12


beta <- c(0.5,0.5)
nsim <- 1000

timing <- system.time({results <- doMonteCarlo(nsim, T, n, beta, DGP = "K3")})
print(timing)



```



